---
Name: rootroutes
Before: '*'
---
Director:
  rules:
    '': 'Controller'
---
Name: coreroutes
Before: '*'
After:
  - '#rootroutes'
  - '#modelascontrollerroutes'
---
Director:
  rules:
    'Security//$Action/$ID/$OtherID': 'Security'
    '$Controller//$Action/$ID/$OtherID':  '*'
    'dev': 'DevelopmentAdmin'
    'interactive': 'SapphireREPL'
---
Name: adminroutes
Before: '*'
After:
  - '#rootroutes'
  - '#coreroutes'
  - '#modelascontrollerroutes'
---
Director:
  rules:
    'admin': 'AdminRootController'
